name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    # - name: Login to Docker Hub
    #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build Docker image
    #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/respsoft-angular:1.0 .

    # - name: Push Docker image
    #   run: docker push ${{ secrets.DOCKER_USERNAME }}/respsoft-angular:1.0




      # Configure AWS CLI with credentials from secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 # Replace with your AWS region, e.g., us-west-2

      # Log in to AWS ECR
    - name: Login to Amazon ECR
      id: login-ecr
      run: |                    
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 211253560212.dkr.ecr.ap-southeast-2.amazonaws.com
          
      # Build and push your Docker image to ECR
    - name: Build and push Docker image
      run: |                    
          docker build -t nginx-for-sapi01 .          
          docker tag nginx-for-sapi01:0.1 211253560212.dkr.ecr.ap-southeast-2.amazonaws.com/nginx-for-sapi01:0.1          
          docker push 211253560212.dkr.ecr.ap-southeast-2.amazonaws.com/nginx-for-sapi01:0.1
